#!/bin/bash

export LD_LIBRARY_PATH=/home/oneway/graphviz/lib

rsync -avz -e ssh oneway@bw7:/var/log/squid/access.log.0 /home/oneway/mc/logs4daisy/bw7-access.log.0
#rsync -avz -e ssh oneway@phx2:/var/log/squid/access.log.0 /home/oneway/mc/logs4daisy/phx2-access.log.0
#rsync -avz -e ssh oneway@nlong:/var/log/squid/access.log /home/oneway/mc/logs4daisy/nlong-access.log
hr=`date +%H`
ymdh=`date +%y%m%d%H`
#scp phx2:/var/log/squid/pho2-ref-$ymdh.dot /home/oneway/mc/phx2/ref-$hr.dot 
scp bw7:/var/log/squid/BW7-ref-$ymdh.dot /home/oneway/mc/bw7/ref-$hr.dot

#for host in phx2 bw7; do 
for host in bw7; do 
path=/home/oneway/mc/$host
#/home/oneway/graphviz/bin/dot -Timap -o$path/$hr.map -Tgif -o$path/$hr.gif $path/ref-$hr.dot
/home/oneway/graphviz/bin/dot -Timap -o$path/$hr.map -Tpng -o$path/$hr.png $path/ref-$hr.dot
cat > /home/oneway/mc/$host/graph$hr.html <<EOF
<html>
<head>
<title>system monitoring</title>
</head>
<body>
<!--
generated by
~/graphviz/bin/dot -Timap -ophx2.map -Tgif -ophx2.gif pho2-ref-graph.dot
-->
<a href="$hr.map"><img src="$hr.png" ismap></a>
<br><br><br>
</body>
</html>

EOF
done
